all :
	gcc *.c ../needs/gnl/*.c ../needs/libft/*.c

# NAME =	pipex.a
# SRCS =	*.c\
# 		../needs/gnl/*.c\
# 		../needs/libft/*.c
# OBJS =	*.o
# NAME = pipex.a



# all	:	${NAME}

# ${NAME} :	toObject
# 	gcc ${OBJS} -o a.out


# toObject :
# 	gcc ${SRCS} -c

# clean :
# 	rm ${OBJS} *.out	